### ISSUE TITLE
Error when trying to compile 

### ISSUE THREAD

**Issue by Noggo123** [Jurij15/FortniteLauncherV2#1]
![Skjermbilde 2023-08-05 191624](https://github.com/Jurij15/FortniteLauncherV2/assets/98756877/79e83e8d-b4dd-4c31-a05c-abf55a250424)

**Comment by Jurij15** [comment]
Add this to your nuget packages sources: https://pkgs.dev.azure.com/dotnet/CommunityToolkit/_packaging/CommunityToolkit-Labs/nuget/v3/index.json

More info here: https://github.com/CommunityToolkit/Labs-Windows

**Comment by Noggo123** [comment]
> Add this to your nuget packages sources: https://pkgs.dev.azure.com/dotnet/CommunityToolkit/_packaging/CommunityToolkit-Labs/nuget/v3/index.json
> 
> More info here: https://github.com/CommunityToolkit/Labs-Windows

Thanks it now works!
