### ISSUE TITLE
Need some help!

### ISSUE THREAD

**Issue by crpnterr** [Jurij15/FortniteLauncherV2#2]
Hey, when I press on play in the navigation bar, the app crashes. Is there a way to fix this issue?

**Comment by crpnterr** [comment]
...

**Comment by Jurij15** [comment]
On the latest commit, i was redesiging the play page and it is not finished.

**Comment by crpnterr** [comment]
> On the latest commit, i was redesiging the play page and it is not finished.

Whats next for the launcher?

**Comment by Jurij15** [comment]
I have started a complete rewrite, but started doing some other things. I will finish it at some point.
